### ISSUE TITLE
Relative Positional Encoding

### ISSUE THREAD

**Issue by romulus0914** [csrhddlam/axial-deeplab#4]
Thanks for your great work!

I have some questions regarding relative positional encoding.
I believe that relative positional encoding is proposed in [Self-Attention with Relative Position Representations](https://arxiv.org/pdf/1803.02155.pdf) and it could formulate as
```
y = sigma( softmax( q * (k + r^k) ) * (v + r^v) )
```
in a simplified version. In [Stand-Alone Self-Attention in Vision Models](https://arxiv.org/pdf/1906.05909.pdf), the self-attention layer omits `r^v` and therefore
```
y = sigma( softmax( q * k + q * r^k ) * v )
```
where `q * (k + r^k)` is unfolded to `q * k + q * r^k` and the superscript `k` in `r^k` is omitted in the paper of 'Stand-Alone Self-Attention in Vision Models'.
For the same reason, adding relative positional information to `q` and `v` should be unfolded to
```
y = sigma( softmax( q * k + q * r^k + k * r^q + r^q * r^k ) * (v + r^v) )
```
instead of
```
y = sigma( softmax( q * k + q * r^q + k * r^k ) * (v + r^v) )
```
as the Eq. (3) in the paper.

Please point it out if I misunderstood.

BTW, I suggest to cite 'Self-Attention with Relative Position Representations' in Sec. 3.1.

**Comment by csrhddlam** [comment]
Thanks for your comments and suggestion.

Your re-formulation is correct. But I don't see how
`y = sigma( softmax( q * k + q * r^k + k * r^q + r^q * r^k ) * (v + r^v) )
`
is different from
`y = sigma( softmax( q * k + q * r^q + k * r^k ) * (v + r^v) )
`

because
1. The 'r^k' you mentioned in the two papers is called `r^q` in our paper.
2. The notation of `r^k` and `r^q` does not matter because they are simply two learnable vectors. You could use any name for them.
3. The additional bias term `r^q * r^k` is simply an input-agnostic relative positional bias. And I don't think omitting this term makes much difference.

In addition, we were not aware of the [Self-Attention with Relative Position Representations](https://arxiv.org/pdf/1803.02155.pdf) when we formulated it. So we did not follow the tradition that relative positional embeddings are added to `q` or `k`. Instead, we focused directly on the unfolded formulation and added `k` dependent terms to it. And we simply call the vector that will be multiplied with `k`, `r^k`.

**Comment by romulus0914** [comment]
Thanks for your reply!

Indeed, there is no difference between them in the implementations.

Thanks again.
